export const mockInfoItems = [
  {
    id: 1,
    title: "AI Scaling Laws Breakthrough",
    source: "Nature Journal",
    type: "paper",
    category: "academic",
    freshness: 5,
    depth: 5,
    alpha: 2,
    x402Endpoint: "/content/nature-ai-paper",
    price: "$0.0001",
    preview:
      "Recent findings show that transformer models scale predictably...",
  },
  {
    id: 2,
    title: "Solana DEX Volume Surge +300%",
    source: "The Block",
    type: "news",
    category: "crypto",
    freshness: 5,
    depth: 3,
    alpha: 5,
    x402Endpoint: "/content/solana-dex-data",
    price: "$0.0002",
    preview: "Real-time DEX aggregator data shows massive buying pressure...",
  },
  {
    id: 3,
    title: "Climate Tech Investment Report Q4 2024",
    source: "McKinsey",
    type: "report",
    category: "industry",
    freshness: 3,
    depth: 5,
    alpha: 1,
    x402Endpoint: "/content/climate-report",
    price: "$0.0005",
    preview: "Comprehensive 150-page analysis of climate tech sector...",
  },
  {
    id: 4,
    title: "Elon Musk's Latest Tweet Storm",
    source: "Twitter/X",
    type: "social",
    category: "entertainment",
    freshness: 5,
    depth: 1,
    alpha: 1,
    x402Endpoint: "/content/musk-tweets",
    price: "$0.00005",
    preview: "Just posted 15 random tweets about everything...",
  },
  {
    id: 5,
    title: "Monad Mainnet Launch Analysis",
    source: "Messari",
    type: "research",
    category: "crypto",
    freshness: 4,
    depth: 4,
    alpha: 4,
    x402Endpoint: "/content/monad-analysis",
    price: "$0.0003",
    preview:
      "Deep dive into Monad's parallel execution and investment potential...",
  },
  {
    id: 6,
    title: "Stealth AI Startup Raises $100M",
    source: "TechCrunch",
    type: "news",
    category: "ai",
    freshness: 5,
    depth: 2,
    alpha: 3,
    x402Endpoint: "/content/ai-startup-news",
    price: "$0.00015",
    preview: "Former OpenAI researchers secure massive Series A...",
  },
  {
    id: 7,
    title: "SEC Crypto Regulation Framework Released",
    source: "SEC.gov",
    type: "regulation",
    category: "crypto",
    freshness: 5,
    depth: 4,
    alpha: 4,
    x402Endpoint: "/content/crypto-regulation",
    price: "$0.00025",
    preview:
      "Comprehensive 64-page framework clarifies digital asset status...",
  },
  {
    id: 8,
    title: "Google Quantum Supremacy Milestone",
    source: "Nature",
    type: "paper",
    category: "academic",
    freshness: 4,
    depth: 5,
    alpha: 2,
    x402Endpoint: "/content/quantum-computing",
    price: "$0.0004",
    preview:
      "127-qubit quantum computer solves practical problem 1000x faster...",
  },
];
